beta: 0.05
bf16: true
dataset_mixer:
  princeton-nlp/llama3-ultrafeedback: 1.0
dataset_splits:
- train
- test
do_eval: true
eval_steps: 400
evaluation_strategy: steps
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Ejafa/phi-3-mini-128k-instruct-dpo-lr-5e-07
learning_rate: 5.0e-07
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
model_name_or_path: microsoft/Phi-3-mini-128k-instruct
num_train_epochs: 1
optim: adamw_torch
output_dir: dpo/phi-3-mini-128k-instruct-dpo-lr-5e-07
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
preprocessing_num_workers: 12
push_to_hub: true
report_to:
- tensorboard
- wandb
run_name: phi-3-mini-128k-instruct-dpo-lr-5e-07
save_steps: 1000000
save_strategy: steps
save_total_limit: 20
seed: 42
torch_dtype: bfloat16
trust_remote_code: true
use_flash_attention_2: true
warmup_ratio: 0.1
